# Generated by Django 2.0.7 on 2018-07-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtable',
            name='nm',
            field=models.CharField(max_length=10, null=True, verbose_name='Phone_number'),
        ),
    ]
